### ISSUE TITLE
Mocked services are undefined in component ngOnInit()

### ISSUE THREAD

**Issue by LukaIvicevic** [dvabuzyarov/moq.ts#132]
I'm not sure if there's something I'm doing wrong or this is a bug. Mocked service that I inject to my component tests are `undefined` during `ngOnInit()`. Thank you.

# Expected Behavior

Mocked injected services are not undefined in component `ngOnInit()`

# Current Behavior

Mocked injected services are undefined in `ngOnInit()`

![Example](https://user-images.githubusercontent.com/30665370/60835943-04d2e680-a18a-11e9-96c8-0ea985de64b1.png)

# Sample code

Component:
```
import { Component, OnInit } from '@angular/core';
import { AppStateService } from 'projects/shared/src/services/app-state.service';

@Component({
    selector: 'test-comp',
    templateUrl: './test-comp.component.html',
    styleUrls: ['./test-comp.component.scss']
})
export class TestCompComponent implements OnInit {

    constructor(
        private readonly appStateService: AppStateService
    ) { }

    ngOnInit() {
        const length = this.appStateService.products.length;
    }

}
```
Service:
```
@Injectable({
    providedIn: 'root'
})
export class AppStateService {
    public products: Product[];
    ....
}

```
Test:
```
import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import { TestCompComponent } from './test-comp.component';
import { Mock } from 'moq.ts';
import { AppStateService } from 'projects/shared/src/services/app-state.service';

describe('TestCompComponent', () => {
    let component: TestCompComponent;
    let fixture: ComponentFixture<TestCompComponent>;
    let appStateServiceMock: Mock<AppStateService>;

    beforeEach(async(() => {
        appStateServiceMock = new Mock<AppStateService>();
        TestBed.configureTestingModule({
            declarations: [TestCompComponent],
            providers: [{ provide: AppStateService, useValue: appStateServiceMock.object() }]
        })
            .compileComponents();
    }));

    beforeEach(() => {
        appStateServiceMock
            .setup(x => { x.products = [] })
            .returns(true);
        fixture = TestBed.createComponent(TestCompComponent);
        component = fixture.componentInstance;
        fixture.detectChanges();
    });

    it('should create', () => {
        expect(component).toBeTruthy();
    });
});
```

**Comment by LukaIvicevic** [comment]
I found the problem.
```
appStateServiceMock
            .setup(x => { x.products = [] })
            .returns(true);
```
to
```
appStateServiceMock
            .setup(x => x.products)
            .returns([]);
```
and the test passes. Was my previous syntax used incorrectly?

**Comment by dvabuzyarov** [comment]
appStateServiceMock
            .setup(x => { x.products = [] })
            .returns(true);

this setup is for property writing, the returned value controls the successful of this operation. See this [Set Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/set).

If you have any other question do not hesitate to reach me out.

ps I am also working with angular and created a package to setup test environment. It could be helpful for you as well. https://github.com/dvabuzyarov/ng-auto-moq

**Comment by LukaIvicevic** [comment]
I see. So in that example, `appStateService.products` would only be allowed to be set to `[]` and would otherwise fail the test. If the same example was changed to `.returns(false)` then `appStateService.products` explicitly could not be set to `[]`. Do I have this right?

Thank you for your time.

**Comment by dvabuzyarov** [comment]
You are right in general. The only thing is that [] is a reference object and the setup works only for that instance. [Compare objects by value](https://github.com/dvabuzyarov/moq.ts/wiki/How-to-compare-object-by-value-not-by-a-reference%3F)
