### ISSUE TITLE
Question about @angular/core dependency

### ISSUE THREAD

**Issue by robert-ursu-ownzones** [dvabuzyarov/moq.ts#324]
Hi,

I noticed that since version 6.3.x this lib has an hidden dependency on `@angular/core`. I use this lib in an angular free project and I do not want to pollute it with unnecessary dependencies. Is it possible to make this lib independent of `@angular/core`?

**Comment by dvabuzyarov** [comment]
Hi,

the lib is using @angular/core internally and you don't need to install this package. It is really internal stuff. Can you give a little more information why do you have such concern?

**Comment by robert-ursu-ownzones** [comment]
![image](https://user-images.githubusercontent.com/55983561/82345969-904e1280-99fe-11ea-8f52-ce98dfa5bbc5.png)
This happens when I upgrade from 6.2.0 to 6.3.1. This is the concern

**Comment by dvabuzyarov** [comment]
I see the issue. Thanks for the feedback, I will see what can I do.

**Comment by dvabuzyarov** [comment]
@robert-ursu-ownzones It is fixed.
