### ISSUE TITLE
NodeJS warnings "UnhandledPromiseRejectionWarning" when mocking async rejections

### ISSUE THREAD

**Issue by anton-johansson** [dvabuzyarov/moq.ts#586]
I really love the new API for mocking async functions. However, whenever I mock an async rejection, I get something like this in my log:
```
(node:499006) UnhandledPromiseRejectionWarning: TypeError: unhandled error
(Use `node --trace-warnings ...` to show where the warning was created)
(node:499006) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:499006) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Here is what my mock looks like:
```ts
const myService = new Mock<MyService>(MyService.prototype)
    .setup(async x => x.myFunctionCall("my-param")).throwsAsync(new TypeError("mocked error"))
    .object();
```

The mocked function does not even need to be actually used/called in my test/code, the warning comes directly when mocking.

The only issue with this is that it floods my log when running all my tests. It would be nice with a way to rid of it. I see two options:

- Somehow have `moq.ts` "simulate" catching the value when mocking. I'm not sure if this is even technically possible, as I don't know how things work under the hood.
- Disable the warning when running tests. There is a NodeJS CLI argument - `--unhandled-rejections=none` - however, I can't really set this in a good way for just my tests. I'd have to manually use it when running `npm test`, and that feels like a hassle.

Any ideas or suggestions?

**Comment by dvabuzyarov** [comment]
@anton-johansson when a rejected promise is create it expected a catch subscription. It throws Unhandled promise rejection when the subscription is missed. throwsAsync creates a real rejected promise, so this leads to the exception if it is not handled. This is a common behaviour and don't think it should be somehow fixed on the library side. You can try to change it according to your needs:
```typescript
export class CustomRejectedPromiseFactory implements InjectionFactory {
    constructor() {
        return this.factory() as any;
    }
    
    factory() {
        return <T>(value: T) => {
            const promise = Promise.reject<T>(value);
            promise.then = promise.then.bind(promise);
            promise.catch = promise.catch.bind(promise);
            promise.finally = promise.finally.bind(promise);
            // return promise; <-- current implementation
            return promise.catch(() => undefined);
        };
    }
}

  const injectorConfig = new EqualMatchingInjectorConfig([], [
      {
          provide: RejectedPromiseFactory,
          useClass: CustomRejectedPromiseFactory,
          deps: []
      },
  ]);

 Mock.options = {injectorConfig};
```

obviously this implementation will fix the issue, but will not rise an expected exception within try/catch block.

Probably one option would be do not provided a setup with throwsAsync until you really want to test it. Replace with returnsAsync(undefined).

**Comment by anton-johansson** [comment]
Thanks again for the detailed response. I don't really want to automatically catch, because I do have a lot of tests for different things. I would also like to keep all my mocks in a single `beforeEach` to keep things structured and simple to read. I decided to go for this for now:

`package.json`:
```
{
  "scripts": {
    "test": "node --unhandled-rejections=none ./node_modules/jest/bin/jest.js"
  }
}
```

Not optimal, but I at least lose the spammy output when running all tests. :) It will do for now, thanks!
