### ISSUE TITLE
How to mock function of type 'void'?

### ISSUE THREAD

**Issue by ManfredLange** [dvabuzyarov/moq.ts#846]
I tried this:
```typescript
const responseMock = new Mock<Response>()
         .setup(instance => instance.status(422));
```
which creates a mock of type `IPresetBuilder<...>`.

When I try this:
```TypeScript
const responseMock = new Mock<Response>()
         .setup(instance => instance.status(422))
         .returns;
```
it compiles but `responseMock.object()` does not exist. Also, a function of type `void` does not really return anything?

Therefore the question: how to mock a function of type `void`? Would you mind adding an example to the set of existing examples in the README.md file, please?

**Comment by dvabuzyarov** [comment]
Hello, what would be the purpose of that?
Usually if you have a void return function you  would need just ensure that it was invoked with specific parameters.

Typical usage: 
``` typescript
const mock = new Mock<Response>();
const mockedFunc = mock.object();
mockedFunc(422);

mock.verify(instance => instance(422), Times.Once());
```
