### ISSUE TITLE
Reset Mock Instance Call Count

### ISSUE THREAD

**Issue by rstolys** [dvabuzyarov/moq.ts#853]
I have multiple tests calling a single mock method to test various test cases. After each test I want to reset the mock call count so that I can verify that it is called each time. 

I don't seem to see this functionality in moq.ts but it does appear to be available in the C# version (see link below). Is this something that is available and I don't know how to use or a feature that could be added in the future?

https://stackoverflow.com/questions/4163679/reset-mock-verification-in-moq

**Comment by dvabuzyarov** [comment]
There is no way to reset the tracked interactions at this moment.
I will add it in the next release, as I finished with ES module migration.

**Comment by dvabuzyarov** [comment]
There is no need to implement this feature, as it could be done in the current release. Please, see the code bellow.

```typescript
import { EqualMatchingInjectorConfig, Expression, Mock, TrackedAction, Tracker } from "moq.ts";
import { SequenceId } from "moq.ts/internal";

export class CustomTracker {
  private log: TrackedAction[] = [];

  constructor(private sequenceId: SequenceId) {

  }

  public add(action: Expression): void {
    const record = {id: this.sequenceId.next(), expression: action};
    this.log.push(record);
  }

  /**
   * Returns recorded interactions.
   */
  public get(): TrackedAction[] {
    return [...this.log];
  }

  public interactions(): Expression[] {
    return this.get().map(record => record.expression);
  }

// an extra method that resets the interactions
  reset(){
    this.log = [];
  }
}
Mock.options = {injectorConfig: new EqualMatchingInjectorConfig([], [
    {provide: Tracker, useClass: CustomTracker, deps: [SequenceId]}
  ])};
```

and after in a test
```typescript
it("A test", () => {
    var mock = new Mock<() => undefined>()
      .setup(instance => instance())
      .returns([]);

    mock.object()();
    const tracker = mock.resolve(Tracker) as CustomTracker;
    tracker.reset();
// would rise an error
    mock.verify(instance => instance());
  });
```
